### ISSUE TITLE
按照《通用规范汉字表》顺序，每种拆法一个文件。

### ISSUE THREAD

**Issue by xxhg** [kfcd/chaizi#6]
可以按照《通用规范汉字表》顺序吗，每种拆法单独一个文件。（http://www.gov.cn/zwgk/2013-08/19/content_2469793.htm）

**Comment by dohliam** [comment]
> http://www.gov.cn/zwgk/2013-08/19/content_2469793.htm

"您訪問的頁面不存在或已刪除"

> 每種拆法單獨一個文件

那幾萬字未免有點亂……
