### ISSUE TITLE
如何拆分？

### ISSUE THREAD

**Issue by Pan-BR** [kfcd/chaizi#7]
我想问一下，这些收录的汉字及其对应的拆字是人工拆分后收集的还是程序拆分的呀？

**Comment by dohliam** [comment]
人工拆分。

**Comment by Pan-BR** [comment]
好的，知道啦。感谢～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kfcd/chaizi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月5日(星期六) 晚上8:55
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [kfcd/chaizi] 如何拆分？ (Issue #7)





 
人工拆分。

**Comment by Pan-BR** [comment]
您好，还有一个问题想问一下：拆字的时候是遵循什么原则呀？比如从上到下 从左到右。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liam Doherty ***@***.***&gt;
发送时间: 2023年8月5日 20:57
收件人: kfcd/chaizi ***@***.***&gt;
抄送: Pan-BR ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [kfcd/chaizi] 如何拆分？ (Issue #7)





 
Closed #7 as completed.

**Comment by dohliam** [comment]
那當然是要看字而定。
